pipeline {
    agent { label 'built-in' }

    stages {
        stage('Deploy Redis') {
            steps {
                sh 'docker rm $(docker stop $(docker ps -a -q --filter name=redis --format="{{.ID}}")) || true'
                sh '''docker run --name redis -d \
                    --network consig1 \
                    --restart unless-stopped \
                    -v redis-data:/data \
                    -p 6379:6379 \
                    redis:7 \
                    redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru'''
            }
        }
        stage('Health Check') {
            steps {
                sh 'sleep 3 && docker exec redis redis-cli ping'
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
